import { z } from 'zod';

export const billItemSchema = z.object({
  productId: z.string().uuid(),
  quantityMoved: z.number().int().positive(), // will be negated when writing to inventory
});

export const createBillSchema = z.object({
  // bill_number is generated by backend (B-000000000001 style)
  bill_number: z.string().min(1).optional(),
  date: z.union([z.string(), z.date()]),
  payment_method: z.string().min(1),
  customer_name: z.string().optional().nullable(),
  customer_type: z.enum(['local', 'foreigner']).optional(),
  order_type: z.string().optional().nullable(),
  table_number: z.string().optional().nullable(),
  service_charge_percentage: z.union([z.number(), z.string()]).optional().nullable(),
  service_charge_amount: z.union([z.number(), z.string()]).optional().nullable(),
  total: z.union([z.number(), z.string()]),
  cashier_name: z.string().min(1),
  item_count: z.number().int().min(0),
  credit_note: z.string().optional().nullable(),
  cash_given: z.union([z.number(), z.string()]),
  balance_given: z.union([z.number(), z.string()]),
  tax: z.union([z.number(), z.string()]).optional().nullable(),
});

export const createBillWithItemsSchema = createBillSchema.extend({
  items: z.array(billItemSchema).min(1),
});

export const billQuerySchema = z
  .object({
    billNo: z.string().optional(),
    // Dates accepted as YYYY-MM-DD or full ISO; leave parsing to service but ensure they're strings here
    dateFrom: z.string().optional(),
    dateTo: z.string().optional(),
    // Coerce common boolean representations from query string to boolean
    today: z.preprocess((val) => {
      if (val === 'true' || val === true) return true;
      if (val === 'false' || val === false) return false;
      return undefined;
    }, z.boolean().optional()),
    paymentMethod: z.string().optional(),
    page: z.coerce.number().int().positive().optional(),
    pageSize: z.coerce.number().int().positive().optional(),
    search: z.string().optional(),
  })
  // Don't allow mixing `today` with explicit dateFrom/dateTo to avoid ambiguity
  .refine((d) => !(d.today && (d.dateFrom || d.dateTo)), {
    message: 'today cannot be used with dateFrom or dateTo',
    path: ['today'],
  })
  // If both dates provided ensure from <= to
  .refine((d) => {
    if (d.dateFrom && d.dateTo) {
      const from = new Date(d.dateFrom);
      const to = new Date(d.dateTo);
      return !isNaN(from.getTime()) && !isNaN(to.getTime()) && from.getTime() <= to.getTime();
    }
    return true;
  }, { message: 'dateFrom cannot be after dateTo', path: ['dateFrom', 'dateTo'] });

export const updateBillPaymentSchema = z.object({
  payment_method: z.string().optional(),
  cash_given: z.union([z.number(), z.string()]).optional().nullable(),
  balance_given: z.union([z.number(), z.string()]).optional().nullable(),
  credit_note: z.string().optional().nullable(),
  customer_name: z.string().optional().nullable(),
  tax: z.union([z.number(), z.string()]).optional().nullable(),
  total: z.union([z.number(), z.string()]).optional().nullable(),
});
