import { Product } from '@/types/pos';

export const generateProducts = (): Product[] => {
  const products: Product[] = [
    // Beverages
    {
      id: 'prod-001',
      name: 'Coca Cola 500ml',
      category: 'Beverages',
      price: 150,
      cost: 100,
      stock: 45,
      minStock: 20,
      barcode: '8901234567890',
      description: 'Refreshing cola drink',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-002',
      name: 'Pepsi 500ml',
      category: 'Beverages',
      price: 140,
      cost: 95,
      stock: 8,
      minStock: 20,
      barcode: '8901234567891',
      description: 'Popular cola beverage',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-003',
      name: 'Sprite 500ml',
      category: 'Beverages',
      price: 140,
      cost: 95,
      stock: 60,
      minStock: 20,
      barcode: '8901234567892',
      description: 'Lemon-lime flavored drink',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-004',
      name: 'Orange Juice 1L',
      category: 'Beverages',
      price: 320,
      cost: 250,
      stock: 5,
      minStock: 15,
      barcode: '8901234567893',
      description: 'Fresh orange juice',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-005',
      name: 'Mineral Water 1L',
      category: 'Beverages',
      price: 80,
      cost: 50,
      stock: 120,
      minStock: 50,
      barcode: '8901234567894',
      description: 'Pure mineral water',
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Bakery
    {
      id: 'prod-006',
      name: 'White Bread',
      category: 'Bakery',
      price: 120,
      cost: 80,
      stock: 25,
      minStock: 15,
      barcode: '8901234567895',
      description: 'Fresh white bread',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-007',
      name: 'Whole Wheat Bread',
      category: 'Bakery',
      price: 140,
      cost: 95,
      stock: 18,
      minStock: 15,
      barcode: '8901234567896',
      description: 'Healthy whole wheat bread',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-008',
      name: 'Chocolate Cookies 200g',
      category: 'Bakery',
      price: 250,
      cost: 180,
      stock: 35,
      minStock: 10,
      barcode: '8901234567897',
      description: 'Delicious chocolate cookies',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-009',
      name: 'Butter Cake',
      category: 'Bakery',
      price: 450,
      cost: 320,
      stock: 3,
      minStock: 10,
      barcode: '8901234567898',
      description: 'Rich butter cake',
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Dairy
    {
      id: 'prod-010',
      name: 'Fresh Milk 1L',
      category: 'Dairy',
      price: 280,
      cost: 210,
      stock: 40,
      minStock: 25,
      barcode: '8901234567899',
      description: 'Fresh full cream milk',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-011',
      name: 'Yogurt 400g',
      category: 'Dairy',
      price: 180,
      cost: 130,
      stock: 30,
      minStock: 20,
      barcode: '8901234567900',
      description: 'Creamy yogurt',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-012',
      name: 'Cheddar Cheese 200g',
      category: 'Dairy',
      price: 650,
      cost: 480,
      stock: 15,
      minStock: 10,
      barcode: '8901234567901',
      description: 'Premium cheddar cheese',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-013',
      name: 'Butter 250g',
      category: 'Dairy',
      price: 380,
      cost: 280,
      stock: 6,
      minStock: 12,
      barcode: '8901234567902',
      description: 'Pure butter',
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Snacks
    {
      id: 'prod-014',
      name: 'Potato Chips 100g',
      category: 'Snacks',
      price: 120,
      cost: 80,
      stock: 55,
      minStock: 30,
      barcode: '8901234567903',
      description: 'Crispy potato chips',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-015',
      name: 'Chocolate Bar 50g',
      category: 'Snacks',
      price: 95,
      cost: 65,
      stock: 80,
      minStock: 40,
      barcode: '8901234567904',
      description: 'Milk chocolate bar',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-016',
      name: 'Peanuts 200g',
      category: 'Snacks',
      price: 180,
      cost: 130,
      stock: 25,
      minStock: 15,
      barcode: '8901234567905',
      description: 'Roasted peanuts',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-017',
      name: 'Biscuits 300g',
      category: 'Snacks',
      price: 150,
      cost: 105,
      stock: 4,
      minStock: 20,
      barcode: '8901234567906',
      description: 'Cream biscuits',
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Food
    {
      id: 'prod-018',
      name: 'Basmati Rice 5kg',
      category: 'Food',
      price: 1200,
      cost: 900,
      stock: 20,
      minStock: 10,
      barcode: '8901234567907',
      description: 'Premium basmati rice',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-019',
      name: 'Pasta 500g',
      category: 'Food',
      price: 220,
      cost: 160,
      stock: 35,
      minStock: 15,
      barcode: '8901234567908',
      description: 'Italian pasta',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-020',
      name: 'Cooking Oil 1L',
      category: 'Food',
      price: 450,
      cost: 350,
      stock: 28,
      minStock: 15,
      barcode: '8901234567909',
      description: 'Vegetable cooking oil',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-021',
      name: 'Sugar 1kg',
      category: 'Food',
      price: 180,
      cost: 140,
      stock: 50,
      minStock: 25,
      barcode: '8901234567910',
      description: 'White sugar',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-022',
      name: 'Salt 1kg',
      category: 'Food',
      price: 80,
      cost: 55,
      stock: 60,
      minStock: 30,
      barcode: '8901234567911',
      description: 'Iodized salt',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-023',
      name: 'Instant Noodles',
      category: 'Food',
      price: 65,
      cost: 45,
      stock: 7,
      minStock: 30,
      barcode: '8901234567912',
      description: 'Quick meal instant noodles',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  return products;
};

export const mockProducts = generateProducts();
